module.exports = {
  env: {
    CLOUD_NAME: process.env.CLOUD_NAME,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    CLOUDINARY_API_KEY: CLOUDINARY_API_KEY,
    PUBNUB_PUBLISH_KEY: process.env.PUBNUB_PUBLISH_KEY,
    PUBNUB_SUBSCRIBE_KEY: process.env.PUBNUB_SUBSCRIBE_KEY,
    PUBNUB_SECRET_KEY: process.env.PUBNUB_SECRET_KEY,
    TWITCH_AUTH_TOKEN: process.env.TWITCH_AUTH_TOKEN,
    TWITCH_CHANNEL: process.env.TWITCH_CHANNEL,
    TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID,
    TWITCH_ACCESS_TOKEN: process.env.TWITCH_ACCESS_TOKEN,
    TWITCH_REFRESH_TOKEN: process.env.TWITCH_REFRESH_TOKEN,
    CALLBACK_URL: process.env.CALLBACK_URL,
  },
};
